# Generated by Django 2.1.1 on 2018-10-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilibiliFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30)),
                ('URL', models.CharField(max_length=30)),
            ],
        ),
    ]
