# Generated by Django 2.1.1 on 2018-10-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0002_bilibilifile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilibilifile',
            old_name='URL',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bilibilifile',
            name='title',
            field=models.CharField(default='no title', max_length=30),
        ),
        migrations.AddField(
            model_name='bilibilifile',
            name='uuid',
            field=models.CharField(default='no uuid', max_length=30),
        ),
    ]
