# Generated by Django 2.1.1 on 2018-11-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0004_bilibilifile_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilibilifile',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='bilibilifile',
            name='upload',
            field=models.FileField(upload_to='videos'),
        ),
    ]
