# Generated by Django 2.1.3 on 2018-12-13 21:27

import bilibili.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0006_bilibilifile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilibilifile',
            name='upload',
        ),
        migrations.AddField(
            model_name='bilibilifile',
            name='uploadVideoCover',
            field=models.FileField(default='NOT cover', upload_to=bilibili.models.BilibiliFile.get_cover_path),
        ),
        migrations.AddField(
            model_name='bilibilifile',
            name='uploadVideoFile',
            field=models.FileField(default='NOT Video', upload_to=bilibili.models.BilibiliFile.get_video_path),
        ),
    ]
